### ISSUE TITLE
Configurable defaults

### ISSUE THREAD

**Issue by enstyled** [jasonraimondi/url-to-png#37]
All the [query parameters](https://jasonraimondi.github.io/url-to-png/usage/#query-parameters) have default values! It would be great if these defaults can be configured with environment variables, e.g. `DEFAULT_WIDTH`, `DEFAULT_VIEWPORT_HEIGHT`, etc.

**Comment by jasonraimondi** [comment]
Oh nice yeah good idea, that would be an easy follow up

**Comment by jasonraimondi** [comment]
Oh shoot I accidentally thought this was one of my “brainstorming” issues that had (like #39). I have not implemented this one yet (mostly because I forgot) but would definitely accept a PR for any of these improvements. I can try and get this issue worked on soon now that I remember it is a real request from an end user.
