### ISSUE TITLE
Bug: Arbitrary File Read via Playwright's Screenshot Feature Exploiting File Wrapper

### ISSUE THREAD

**Issue by timoxoszt** [jasonraimondi/url-to-png#47]
Hello @jasonraimondi,

I have a vulnerability report.

Please see the attached PDF for detailed information.

[Arbitrary File Read via Playwright's Screenshot Feature Exploiting File Wrapper.pdf](https://github.com/user-attachments/files/15536336/Arbitrary.File.Read.via.Playwright.s.Screenshot.Feature.Exploiting.File.Wrapper.pdf)

Thanks.

**Comment by jasonraimondi** [comment]
This is amazing, thank you very much for this report! I will get these changes in ASAP.

**Comment by timoxoszt** [comment]
Hello @jasonraimondi,

Would you mind publishing a CVE for this?

**Comment by jasonraimondi** [comment]
Hey @timoxoszt, not entirely sure how to do that. I don't mind doing it, I'm just not sure what to do. Do you have an example you can point me towards?

**Comment by timoxoszt** [comment]
Hey @jasonraimondi,

This guide on GitHub walks through publishing a security advisory, which should include publishing a CVE: https://docs.github.com/en/code-security/security-advisories/working-with-repository-security-advisories/publishing-a-repository-security-advisory

**Comment by timoxoszt** [comment]
Hello @jasonraimondi ,

I hope you're having a good day. I would like to request an update on the status of this CVE. I noticed that [GHSA-665w-mwrr-77q3](https://github.com/jasonraimondi/url-to-png/security/advisories/GHSA-665w-mwrr-77q3) was published last week. If you haven't already submitted a CVE Request, please scroll to the bottom of the advisory form and click **Request CVE.**

![image](https://github.com/jasonraimondi/url-to-png/assets/75104235/d0022ced-e0f2-41d0-b404-75658e51b9d9)

Thank you, and I look forward to hearing from you soon.

**Comment by jasonraimondi** [comment]
Just clicked that button 👍

**Comment by realArcherL** [comment]
I have been contemplating whether FTP or other protocols could serve as useful functionalities, but there may not be a practical reason for it since we are utilizing headless Chrome to capture screenshots. My argument is based on the assumption that this package can function as a service.

The package includes an `ALLOW_LIST` where the host can specify which services the user is permitted to capture screenshots of. By default, capturing screenshots of web services running on localhost, 127.0.0.1, or the [::] is allowed.

I am of the opinion that the package should also have a blacklist due to a potential vulnerability. If someone hosts this on a server, users could then capture screenshots of other web services running locally.
